credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: $2b$12$gcGPVOgqHhwjCAS3J3H.5eDclcDyvjPomYAmdpfNTZbWFQH9hx96u
    support:
      email: support@example.com
      name: Support User
      password: $2b$12$22vXZxb.wBwTPQDsS1A0XuW8LUYQBQtUgeWZK2qNShhDVvWGozkcO

cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name

preauthorized:
  emails:
  - admin@example.com
  - support@example.com
